mysite/urls.py
from django.conf.urls import include, url
from django.contrib import admin

urlpatterns = [
    url(r'^polls/', include('polls.urls')),
    url(r'^admin/', admin.site.urls),
]

polls/urls.py
from django.conf.urls import url

from . import views

app_name = 'polls'
urlpatterns = [
    url(r'^$', views.IndexView.as_view(), name='index'),
    url(r'^add_question/$',views.get_name,name='add_question'),
    url(r'^(?P<pk>[0-9]+)/$', views.DetailView.as_view(), name='detail'),
    url(r'^(?P<pk>[0-9]+)/results/$', views.ResultsView.as_view(), name='results'),
    url(r'^(?P<question_id>[0-9]+)/vote/(?P<message>[a-z]+)/$', views.vote, name='vote'),
    url(r'^user_detail/$',views.view_name,name = 'user_detail'),
    url(r'^login_id/$',views.login_view,name ='login_id'),
    url(r'^sign_up/$',views.signup_view,name ='sign_up'),
    url(r'^log_out/$',views.logout_view,name = 'log_out'),

] 

polls/models.py
import datetime
from django.db import models
from django.utils import timezone
from django.contrib.auth.models import User
from django.conf import settings

class Question(models.Model):
    question_text = models.CharField(max_length=200)
    pub_date = models.DateTimeField('date published')
    
    def __str__(self):
	   return self.question_text
    
    def was_published_recently(self):
        now = timezone.now()
        return now - datetime.timedelta(days = 1) <= self.pub_date <=now
    was_published_recently.admin_order_field = 'pub_date'
    was_published_recently.boolean = True
    was_published_recently.short_description = 'Published recently'


class Choice(models.Model):
    question = models.ForeignKey(Question, on_delete=models.CASCADE)
    choice_text = models.CharField(max_length=200)
    votes = models.IntegerField(default=0)

    def __str__(self):
	    return self.choice_text
        
    def was_published_recently(self):
            now = timezone.now()
            return now - datetime.timedelta(days=1) <= self.pub_date <= now

class VoteDetails(models.Model):
    
    choice = models.ForeignKey(Choice, on_delete=models.CASCADE)
    username = models.ForeignKey(settings.AUTH_USER_MODEL,on_delete =models.CASCADE)
    presentdate = models.DateTimeField(null = False,blank = False)


def test_was_published_recently_with_old_question(self):

    time = timezone.now() - datetime.timedelta(days=30)
    old_question = Question(pub_date=time)
    self.assertEqual(old_question.was_published_recently(), False)

def test_was_published_recently_with_recent_question(self):
    """
    was_published_recently() should return True for questions whose
    pub_date is within the last day.
    """
    time = timezone.now() - datetime.timedelta(hours=1)
    recent_question = Question(pub_date=time)
    self.assertEqual(recent_question.was_published_recently(), True)


class User_details(models.Model):
    first_name = models.CharField(max_length = 50)
    middle_name = models.CharField(max_length = 50)
    last_name = models.CharField(max_length = 50)
    dob = models.DateTimeField(null = True ,blank = True)
    age = models.IntegerField()
    maritalstatus = models.BooleanField(default = False)

polls/forms.py
from django import forms
from .models import Question, Choice  ,User_details
from django.contrib.auth.models import User
from django.contrib.auth import authenticate, login
from django.utils import timezone

class QuestionForm(forms.Form):
    Your_Question = forms.CharField(label='Your_Question',max_length=200)
    Choice_1 = forms.CharField(label = 'Your_Choice1',max_length=50)
    Choice_2 = forms.CharField(label = 'Your_Choice2',max_length=50)
    Choice_3 = forms.CharField(label = 'Your_Choice3',max_length=50, required=False)
    Choice_4 = forms.CharField(label = 'Your_Choice4',max_length=50, required = False)
    Choice_5 = forms.CharField(label = 'Your_Choice5',max_length=50, required = False)
    
    def save(self):
        Question.objects.all()
        q = Question(question_text = self.cleaned_data['Your_Question'],pub_date = timezone.now())
        q.save()
        q.choice_set.create(choice_text = self.cleaned_data['Choice_1'], votes=0)
        q.choice_set.create(choice_text=self.cleaned_data['Choice_2'], votes=0)
        q.choice_set.create(choice_text=self.cleaned_data['Choice_3'], votes=0)
        q.choice_set.create(choice_text=self.cleaned_data['Choice_4'], votes=0)
        q.choice_set.create(choice_text=self.cleaned_data['Choice_5'], votes=0)
        return q


class DetailForm(forms.Form):
    first_name = forms.CharField(label = 'first_name',max_length = 50)
    middle_name = forms.CharField(label = 'middle_name',max_length = 50)
    last_name = forms.CharField(label = 'last_name',max_length = 50)
    dob = forms.DateTimeField(label = 'dob',required = False)
    age = forms.IntegerField(label = 'age')
    maritalstatus = forms.BooleanField(label = 'maritalstatus',required = False)

    def save(self):
        u = User_details(first_name = self.cleaned_data['first_name'],middle_name = self.cleaned_data['middle_name'],last_name = self.cleaned_data['last_name'],dob = self.cleaned_data['dob'],age = self.cleaned_data['age'],maritalstatus = self.cleaned_data['maritalstatus'])
        u.save()


class LoginForm(forms.Form):
    user_name = forms.CharField(label='user_name',max_length=20)
    pass_word = forms.CharField(label = "pass_word", min_length= 5)

    def save(self):
        username = self.cleaned_data['user_name']
        password = self.cleaned_data['pass_word']
        l = authenticate(username=username,password =password)
        return l


class SignUpForm(forms.Form):
    user_name = forms.CharField(label = "user_name",max_length = 20)
    pass_word = forms.CharField(label = "pass_word", min_length = 5)

    def save(self):
        username = self.cleaned_data['user_name']
        password = self.cleaned_data['pass_word']
        s = User.objects.create_user(username,username,password)
        s.save()

polls/views.py
from django.shortcuts import get_object_or_404, render
from django.http import HttpResponseRedirect , HttpResponse ,JsonResponse
from django.core.urlresolvers import reverse
from django.views import generic
from django.utils import timezone
from django.shortcuts import render
from .models import Choice, Question , User_details, VoteDetails
from .forms import QuestionForm , DetailForm, LoginForm, SignUpForm
from django.contrib.auth import authenticate,login,logout
from django.contrib.auth.models import User
from django.contrib.auth.decorators import login_required
from django.contrib.auth.mixins import LoginRequiredMixin
from django.conf import settings
from django.views.decorators.csrf import csrf_exempt
from django.core import serializers
import json


class IndexView(generic.ListView):
    login_url = '/polls/login_id/'
    template_name = 'polls/index.html'

    context_object_name = 'latest_question_list'

    def get_queryset(self):
        return Question.objects.filter(pub_date__lte=timezone.now()).order_by('-pub_date')[:5] 


class DetailView(LoginRequiredMixin,generic.DetailView):
    login_url = '/polls/login_id/'
    model = Question
    template_name = 'polls/detail.html'
    def get_queryset(self):
        return Question.objects.filter(pub_date__lte=timezone.now())


class ResultsView(LoginRequiredMixin,generic.DetailView):
    login_url = '/polls/login_id/'
    model = Question
    template_name = 'polls/results.html'


@login_required(login_url='/polls/login_id/')
@csrf_exempt
def vote(request,question_id,message):
    question = get_object_or_404(Question, pk=question_id)
    Date_detail = VoteDetails()
    current_user = request.user
    try:
        selected_choice = question.choice_set.get(pk=request.POST['choice'])
    except (KeyError, Choice.DoesNotExist):
        return render(request, 'polls/detail.html', {
            'question': question,
            'error_message': "You didn't select a choice.",
        })
    else:
        selected_choice.votes += 1
        selected_choice.save()
        Date_detail.choice_id = selected_choice.id
        Date_detail.username_id = current_user.id
        Date_detail.presentdate = timezone.now()
        Date_detail.save()
    #return HttpResponseRedirect(reverse('polls:results', args=(question.id,)))
    return JsonResponse({"redirect": reverse('polls:results',args=(question.id,))},safe=False)

@login_required(login_url='/polls/login_id/')
@csrf_exempt
def get_name(request):
    if request.method== 'POST':
       form = QuestionForm(request.POST)
       if form.is_valid():
            print("Form is valid")
            ques=form.save()
            #data = serializers.serialize('json',[ques,])
            return JsonResponse({"redirect" : '/polls/'},safe=False)
    else:
        form = QuestionForm()

    return render(request,'polls/Question.html',{'form':form})


@login_required(login_url='/polls/login_id/')
def view_name(request):
    if request.method == 'POST':
        form = DetailForm(request.POST)
        if form.is_valid():
            form.save()
            return JsonResponse({"redirect" :'/polls/'},safe = False)
        else :
            temp = form.errors
            print(temp)
    else:
        form = DetailForm()

    return render(request, 'polls/user.html',{'form': form})

@csrf_exempt
def signup_view(request):
    if request.method == 'POST':
        form = SignUpForm(request.POST)
        if form.is_valid():
            form.save()
            return JsonResponse({"redirect": '/polls/login_id/'},safe=False)        
    else :
        form = SignUpForm()
    return render(request,'polls/signup.html',{'form':form})


@csrf_exempt
def login_view(request):
    form = LoginForm(request.POST or None)
    if request.method =='POST':
        if form.is_valid():
            user = form.save()
            if user is not None:
                if user.is_active:
                    login(request,user)
                    return JsonResponse({"redirect" :'/polls/'},safe = False)
                else:
                    print("The user is Disabled")
            else:
                print("The user is invalid")
        else:
            print("The Form Is Invalid")
    else:        
        form = LoginForm()
    return render(request,'polls/login.html',{'form':form})


@login_required(login_url='/polls/')
def logout_view(request):
    logout(request)
    return HttpResponseRedirect(reverse('polls:'))
    

polls/templates/polls/Question.html
{% load staticfiles %}
<html>
<head>
<meta name="viewport" content="width=device-width, initial-scale=1">      
<link rel="stylesheet" href="https://fonts.googleapis.com/icon?family=Material+Icons">
<link rel="stylesheet" href="{% static 'polls/css/materialize.min.css' %}" type="text/css" />
<script type="text/javascript" src="https://code.jquery.com/jquery-2.1.1.min.js"></script>           
<script src="{% static 'polls/js/materialize.min.js' %}"> </script>
<script type="text/javascript">
    $(document).ready(function() {
    var frm = $('#love');
    var btn = $('#submit');
        btn.click(function (ev){
                        ev.preventDefault();
                        $.ajax({
                                type       : "POST",
                                url        : "/polls/add_question/", 
                                data       :  frm.serialize(), 
                                dataType    : 'json', 
                                success      : function(data) { 
                                                    window.location.href = data.redirect; }
                    });
        });
    });
</script>
</head>
<body>
<div class="row">
<form id='love' class = 'col s12' method='post'>
{% csrf_token %}
<div class="row">
<div class ="input-field column s12">
<input id="Your_Question" type="text" class="validate" name="Your_Question">
<label for="Your_Question">Your_Question</label>
</div>
</div>
<div class="row">
<div class ="input-field column s4">
<input id="Your_Choice1" type="text" class="validate" name="Choice_1">
<label for="Your_Choice1">Your_Choice1</label>
</div>
<div class="input-field column s4">
<input id="Your_Choice2" type="text" class="validate" name="Choice_2">
<label for="Your_Choice2">Your_Choice2</label>
</div>
<div class="input-field column s4">
<input id="Your_Choice3" type="text" class="validate" name="Choice_3">
<label for="Your_Choice3">Your_Choice3</label>
</div>
</div>
<div class="row">
<div class="input-field column s6">
<input id="Your_Choice4" type="text" class="validate" name="Choice_4">
<label for="Your_Choice4">Your_Choice4</label>
</div>
<div class="input-field column s6">
<input id="Your_Choice5" type="text" class="validate" name="Choice_5">
<label for="Your_Choice5">Your_Choice5</label>
</div>
</div>
<button class="btn waves-effect waves-light" id='submit' type="submit" value="Submit">Submit
<i class="material-icons right">send</i>
</button>
</div>
</form>
</div>
</body>
</html>

polls/templates/polls/detail.html
{% load staticfiles %}
<html>
<head>
<meta name="viewport" content="width=device-width, initial-scale=1">      
<link rel="stylesheet" href="https://fonts.googleapis.com/icon?family=Material+Icons">
<link rel="stylesheet" href="{% static 'polls/css/materialize.min.css' %}" type="text/css" />
<script type="text/javascript" src="https://code.jquery.com/jquery-2.1.1.min.js"></script>           
<script src="{% static 'polls/js/materialize.min.js' %}"> </script>
<script type="text/javascript">
    $(document).ready(function() {
    $('.test_class').click(function(ev){
    					ev.preventDefault();
    					var id =  $(this).attr("data-questionid");
    					var frm = $( '[data-formname="' + id + '"]' );
                        $.ajax({
                                type       : "POST",
                                url        : "http://localhost:8000/polls/" + id + "/vote/" + 'message' + "/", 
                                data       :  frm.serialize(), 
                                dataType    : 'json', 
                                success      : function(data) { 
                                                window.location.href = data.redirect; }
                    });
        });
    });
</script>
</head>
<body>
<h1>{{ question.question_text }}</h1>

{% if error_message %}<p><strong>{{ error_message }}</strong></p>{% endif %}
<div class="row">
<form  class="column s12" data-formname="{{question.id}}" method="post">
{% csrf_token %}
{% for choice in question.choice_set.all %}
    <input type="radio" name="choice" id="choice{{ choice.id }}" value="{{ choice.id }}" />
    <label for="choice{{ choice.id }}">{{ choice.choice_text }}</label><br />
{% endfor %}
<button class='btn waves-effect waves-light test_class' data-questionid="{{question.id}}" type="submit" value="Submit">Submit
<i class="material-icons right">send</i>
</button>
</form>
</div>
</body>
</html>

polls/templates/polls/index.html
{% load staticfiles %}
<html>
<head>
<meta name="viewport" content="width=device-width, initial-scale=1">      
<link rel="stylesheet" href="https://fonts.googleapis.com/icon?family=Material+Icons">
<link rel="stylesheet" href="{% static 'polls/css/materialize.min.css' %}" type="text/css" />
<link rel="stylesheet" type="text/css" href="{% static 'polls/css/style.css' %}" />
<script type="text/javascript" src="https://code.jquery.com/jquery-2.1.1.min.js"></script>           
<script src="{% static 'polls/js/materialize.min.js' %}"> </script>
<script type="text/javascript">
    $(document).ready(function() {
    $('.test_class').click(function(ev){
    					ev.preventDefault();
    					var id =  $(this).attr("data-questionid");
    					var frm = $( '[data-formname="' + id + '"]' );
                        $.ajax({
                                type       : "POST",
                                url        : "http://localhost:8000/polls/" + id + "/vote/" + 'message' + "/", 
                                data       :  frm.serialize(), 
                                dataType    : 'json', 
                                success      : function(data) { 
                                                window.location.href = data.redirect; }
                    });
        });
    });
</script>
</head>
<body>
{% if latest_question_list %}     
<ul>
{% for question in latest_question_list %}
<li>  {{ question.question_text }} <br>
{% if error_message %}<p><strong>{{error_message}}</strong></p> {% endif %}
<div class="row">
<form  class="column s12" id='love' method="post" data-formname = "{{question.id}}">
{% csrf_token %}
{% for choice in question.choice_set.all %}
<input type="radio" name="choice" id="choice{{ choice.id }}" value="{{ choice.id }}" />
<label for="choice{{ choice.id }}">{{ choice.choice_text }}</label><br />
{% endfor %}
<button class='btn waves-effect waves-light test_class' id='submit' type="submit" value="Submit" data-questionid="{{question.id}}">Submit
<i class="material-icons right">send</i>
</button>
</form>
</div>
</li>
{% endfor %}
</ul>
{% else %}
<p>No polls are available.</p>
{% endif %}
<a href = "{% url 'polls:add_question' %}"> Add_Question </a> <br><br>
<a href ="{% url 'polls:user_detail' %}"> Get Detail </a><br><br>
<a href ="{% url 'polls:log_out' %}"> Click To LogOut</a>
</body>
</html>

polls/templates/polls/login.html
{% load staticfiles %}
<html>
<head>
<meta name="viewport" content="width=device-width, initial-scale=1">      
<link rel="stylesheet" href="https://fonts.googleapis.com/icon?family=Material+Icons">
<link rel="stylesheet" href="{% static 'polls/css/materialize.min.css' %}" type="text/css" />
<script type="text/javascript" src="https://code.jquery.com/jquery-2.1.1.min.js"></script>           
<script src="{% static 'polls/js/materialize.min.js' %}"> </script>
<script type="text/javascript">
    $(document).ready(function() {
    var frm = $('#love');
    var btn = $('#submit');
        btn.click(function (ev){
                        ev.preventDefault();
                        $.ajax({
                                type       : "POST",
                                url        : "/polls/login_id/", 
                                data       :  frm.serialize(), 
                                dataType    : 'json', 
                                success      : function(data) { 
                                                    window.location.href = data.redirect; }
                    });
        });
    });
</script>
</head>
<body>
<h1 align="center" color="red"><u>This is a Login Form</u></h1>
<div class = "row">
<form class="column s12" id= 'love' action="{% url 'polls:login_id' %}" method="post">
    {% csrf_token %}
    <div class="row">
    <div class= "input-field column s6">
    <input  id="user_name" type="text" class="validate" name="user_name">
    <label for="user_name">User_name</label>
    </div>
    <div class="input-field column s6">
    <input id="pass_word" type="password" class="validate" name="pass_word">
    <label for="pass_word">Pass_Word</label>
    </div>
    </div>
    <button class="btn waves-effect waves-light" id='submit' type="submit" value="Submit">Submit
    <i class="material-icons right">send</i>
    </button>
    </form>
</div>
<a href="{% url 'polls:sign_up' %}"> New User </a>
</body>
</html>

polls/templates/polls/results.html
{% load staticfiles %}
<html>
<head>
<meta name="viewport" content="width=device-width, initial-scale=1">      
<link rel="stylesheet" href="https://fonts.googleapis.com/icon?family=Material+Icons">
<link rel="stylesheet" href="{% static 'polls/css/materialize.min.css' %}" type="text/css" />
<script type="text/javascript" src="https://code.jquery.com/jquery-2.1.1.min.js"></script>           
<script src="{% static 'polls/js/materialize.min.js' %}"> </script>
</head>
<body>

<h1>{{ question.question_text }}</h1>

<ul>
{% for choice in question.choice_set.all %}
<li>{{ choice.choice_text }} -- {{ choice.votes }} vote{{ choice.votes|pluralize }}</li>
{% endfor %}
</ul>
<a href="{% url 'polls:detail' question.id %}">Vote again?</a>
</body>
</html>

polls/templates/polls/signup.html
{% load staticfiles %}
<html>
<head>
<meta name="viewport" content="width=device-width, initial-scale=1">      
<link rel="stylesheet" href="https://fonts.googleapis.com/icon?family=Material+Icons">
<link rel="stylesheet" href="{% static 'polls/css/materialize.min.css' %}" type="text/css" />
<script type="text/javascript" src="https://code.jquery.com/jquery-2.1.1.min.js"></script>           
<script src="{% static 'polls/js/materialize.min.js' %}"> </script>
<script type="text/javascript">
    $(document).ready(function() {
    var frm = $('#love');
    var btn = $('#submit');
        btn.click(function (ev){
                        ev.preventDefault();
                        $.ajax({
                                type       : "POST",
                                url        : "/polls/sign_up/", 
                                data       :  frm.serialize(), 
                                dataType    : 'json', 
                                success      : function(data) { 
                                                    window.location.href = data.redirect; }
                    });
        });
    });
</script>
</head>
<body>
<h1 align="center" color="red"><u>This is a SignUp Form</u></h1>
<h4 align="center" color="yellow"><i><u>"Happy To Have You"</u></i></h4>
<div class = "row">
<form id ='love' class="column s12" action="{% url 'polls:sign_up' %}" method="post">
    {% csrf_token %}
    <div class="row">
    <div class= "input-field column s6">
    <input  id="user_name" type="text" class="validate" name="user_name">
    <label for="user_name">User_name</label>
    </div>
    <div class="input-field column s6">
    <input id="pass_word" type="password" class="validate" name="pass_word">
    <label for="pass_word">Pass_Word</label>
    </div>
    </div>
    <button class="btn waves-effect waves-light" id= 'submit' type="submit" value="Submit">Submit
    <i class="material-icons right">send</i>
    </button>
    </form>
</div>
</body>
</html>

polls/templates/polls/user.html
{% load staticfiles %}
<html>
<head>
<meta name="viewport" content="width=device-width, initial-scale=1">      
<link rel="stylesheet" href="https://fonts.googleapis.com/icon?family=Material+Icons">
<link rel="stylesheet" href="{% static 'polls/css/materialize.min.css' %}" type="text/css" />
<script type="text/javascript" src="https://code.jquery.com/jquery-2.1.1.min.js"></script>           
<script src="{% static 'polls/js/materialize.min.js' %}"> </script>
<script type="text/javascript">
    $(document).ready(function() {
    var frm = $('#love');
    var btn = $('#submit');
        btn.click(function (ev){
                        ev.preventDefault();
                        $.ajax({
                                type       : "POST",
                                url        : "/polls/user_detail/", 
                                data       :  frm.serialize(), 
                                dataType    : 'json', 
                                success      : function(data) { 
                                                    window.location.href = data.redirect; }
                    });
        });
    });
</script>
</head>
<body>
<div class="row">
<form class="col s12"  id='love' action="{% url 'polls:user_detail' %}" method="post">
{% csrf_token %}
<div class="row">
<div class="input-field col s4">
<input  id="first_name" type="text" class="validate" name="first_name">
<label for="first_name">First Name</label>
</div>
<div class = "input-field col s4">
<input  id="middle_name" type="text" class = "validate" name="middle_name">
<label for="middle_name">Middle Name</label>
</div>
<div class="input-field col s4">
<input  id="last_name" type="text" class="validate" name = "last_name">
<label for="last_name">Last Name</label>
</div>
</div>
<div class="row">
<div class="input-field col s12">
<input id="age" type="number" class="validate" name="age">
<label for="age">Age</label>
</div>
</div>
<div class="row">
<div class="input-field col s12"><br>
<input id="dob" type="date" class="datepicker" name="dob"><br>
<label for="dob" >DOB</label>
</div>
</div>
<p>
<input type="checkbox" id="maritalstatus">
<label for="maritalstatus">Marital Status</label>
</p>
<button class="btn waves-effect waves-light" id='submit' type="submit" value="Submit">Submit
<i class="material-icons right">send</i>
</button>
</div>
</form>
</div>
</body>
</html>